gcp_svc_key = "../terraform-svc.json"
gcp_project = "terraform-408108"
gcp_region = "us-east1"
service_account_email= "task5-terraform@terraform-408108.iam.gserviceaccount.com"
bucket_name = "cloud-function-bucket-by-anagha"
